### ISSUE TITLE
Example not Working

### ISSUE THREAD

**Issue by stensmo** [TidierOrg/Tidier.jl#111] opened 2023-08-03 21:22 UTC
In the example below, using a fresh install (no DataFramesMeta package), I had to install DataFramesMeta and then add: 
import DataFramesMeta.Chain

using Tidier
using RDatasets

movies = dataset("ggplot2", "movies");

@chain movies begin
    @mutate(Budget = Budget / 1_000_000)
    @filter(Budget >= mean(skipmissing(Budget)))
    @select(Title, Budget)
    @slice(1:5)
end

**Comment by kdpsingh** [comment] 2023-08-03 22:29
Tidier doesn’t require DataFramesMeta to be installed so I’m not sure why that would be the case. Additionally, Tidier re-exports the `@chain` macro directly from Chain.jl so you shouldn’t need to grab the macro using DataFramesMeta.

I notice that the `M` in `@Mutate` is capitalized. Is that the cause of the error?

Can you share what error you are getting?

**Comment by stensmo** [comment] 2023-08-05 10:28
julia> movies = dataset("ggplot2", "movies");

julia>

julia> @chain movies begin
           @mutate(Budget = Budget / 1_000_000)
           @filter(Budget >= mean(skipmissing(Budget)))
           @select(Title, Budget)
           @slice(1:5)
       end
ERROR: LoadError: UndefVarError: `@chain` not defined
in expression starting at REPL[5]:1

**Comment by stensmo** [comment] 2023-08-05 10:40
After restarting Julia it works

**Comment by kdpsingh** [comment] 2023-08-05 23:29
Glad to hear! Will close this issue.

**Closed** 2023-08-05 23:29 UTC
